# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "apyori" = super.buildPythonPackage rec {
    pname = "apyori";
    version = "1.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5e/62/5ffde5c473ea4b033490617ec5caa80d59804875ad3c3c57c0976533a21a/apyori-1.1.2.tar.gz";
      sha256 = "1v32siqfg5ljgpmmh13v711q4lxch4xzi33068a1navk2k7zzrp2";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
