services:
  postgres:
    image: bitnami/postgresql:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: change_me
    restart: always

  keycloak:
    image: bitnami/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: db_user
      DB_PASSWORD: change_me
      KEYCLOAK_EXTRA_ARGS: --import-realm
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./import:/opt/bitnami/keycloak/data/import

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  api:
    build: ./src/api
    ports:
      - "5000:5000"
    depends_on:
      - keycloak
      - mongodb

  next:
    build: ./src/next
    ports:
      - "3000:3000"
    depends_on:
      - api
      - keycloak



volumes:
  postgres_data:
  mongodb_data:
