version: '3.8'

services:
  db:
    image: mongo
    restart: always
    networks:
      - default
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  web:
    build: .
    ports:
      - "5000:5000"
    restart: always
    networks:
      - default
    depends_on:
      - db

networks:
  default:
    driver: bridge
